.TH foo 1
.SH NAME
foo \- brief description here
.SH USAGE
.B foo [OPTIONS] <ACTION>
.SH DESCRIPTION
Detailed description here.
.SH OPTIONS
.TP
.TP
\fB\-h, --help\fR
.br 
Displays command help.
.SH ARGUMENTS
.TP
.TP 
\fB filename(s) \fR
.br 
File(s) to display or stdin if none specified.
.SH RESTRICTIONS
.TP
None. 
.\" .SH NOTES
.\" .TP
.\" Note text.
.SH EXAMPLES
.TP
foo
.TP
foo -
.TP
foo -xy File1 File2
.SH FILE LOCATIONS 
.TP
/usr/local/bin/foo
Executable 
.TP
/usr/local/share/man/man1/foo.1
Manpage 
.\" .SH AUTHOR
.\" .nf
.\" Robert Primmer (https://github.com/rprimmer)
.fi
